import argparse
import os
from typing import List

import torch
from datasets import Dataset, load_dataset
from peft import LoraConfig, TaskType
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments
from trl import SFTTrainer

try:
    import wandb
except ImportError:  # pragma: no cover - wandb is optional at runtime
    wandb = None


BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_DATASET_PATH = os.path.abspath(
    os.path.join(BASE_DIR, "..", "data", "synthetic_conflict_dataset.jsonl")
)
DEFAULT_OUTPUT_DIR = os.path.abspath(os.path.join(BASE_DIR, "outputs", "sft-run"))
DEFAULT_ADAPTER_OUTPUT_DIR = os.path.abspath(
    os.path.join(BASE_DIR, "models", "gitcat-sft-lora-final")
)
DEFAULT_MODEL_ID = "Qwen/Qwen2.5-Coder-7B-Instruct"
DEFAULT_LORA_TARGET_MODULES = "q_proj,k_proj,v_proj,o_proj"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="GitCat SFT-LoRA training entrypoint",
    )
    parser.add_argument(
        "--model-id",
        default=DEFAULT_MODEL_ID,
        help="HuggingFace base model id. Task 31 default is Qwen2.5-Coder-7B-Instruct.",
    )
    parser.add_argument(
        "--dataset-path",
        default=DEFAULT_DATASET_PATH,
        help="JSONL dataset path generated by build_jsonl.py.",
    )
    parser.add_argument(
        "--output-dir",
        default=DEFAULT_OUTPUT_DIR,
        help="Trainer checkpoint output directory.",
    )
    parser.add_argument(
        "--adapter-output-dir",
        default=DEFAULT_ADAPTER_OUTPUT_DIR,
        help="Final LoRA adapter save directory.",
    )
    parser.add_argument(
        "--dataset-domain",
        choices=["merge", "recommendation"],
        help="Train only a single dataset domain when running focused experiments.",
    )
    parser.add_argument(
        "--feature-type",
        choices=[
            "merge_patch_draft",
            "conflict_explanation",
            "merge_mediation",
            "recommendation",
        ],
        help="Optional feature_type filter for focused SFT runs.",
    )
    parser.add_argument(
        "--recommendation-type",
        choices=["branch_name", "commit_message", "pr_description"],
        help="Optional recommendation subtype filter.",
    )
    parser.add_argument(
        "--max-samples",
        type=int,
        help="Cap dataset size for smoke tests before starting a long GPU run.",
    )
    parser.add_argument("--max-seq-length", type=int, default=2048)
    parser.add_argument("--learning-rate", type=float, default=2e-4)
    parser.add_argument("--per-device-train-batch-size", type=int, default=1)
    parser.add_argument("--gradient-accumulation-steps", type=int, default=8)
    parser.add_argument("--num-train-epochs", type=float, default=1.0)
    parser.add_argument("--max-steps", type=int, default=-1)
    parser.add_argument("--logging-steps", type=int, default=10)
    parser.add_argument("--save-steps", type=int, default=100)
    parser.add_argument("--save-total-limit", type=int, default=2)
    parser.add_argument("--warmup-ratio", type=float, default=0.03)
    parser.add_argument("--weight-decay", type=float, default=0.0)
    parser.add_argument("--lora-r", type=int, default=16)
    parser.add_argument("--lora-alpha", type=int, default=32)
    parser.add_argument("--lora-dropout", type=float, default=0.05)
    parser.add_argument(
        "--lora-target-modules",
        default=DEFAULT_LORA_TARGET_MODULES,
        help="Comma-separated attention module names to adapt with LoRA.",
    )
    parser.add_argument(
        "--torch-dtype",
        choices=["auto", "float16", "bfloat16", "float32"],
        default="auto",
        help="Precision policy for base model loading.",
    )
    parser.add_argument(
        "--report-to",
        choices=["none", "wandb"],
        default="none",
        help="Training report backend. Use wandb only when the runtime is logged in.",
    )
    parser.add_argument(
        "--wandb-project",
        default="gitcat-sft-lora",
        help="Weights & Biases project name when --report-to wandb is used.",
    )
    parser.add_argument(
        "--wandb-run-name",
        default=None,
        help="Optional explicit W&B run name.",
    )
    parser.add_argument(
        "--gradient-checkpointing",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Enable gradient checkpointing to reduce VRAM usage during long SFT runs.",
    )
    return parser.parse_args()


def parse_csv_list(raw_value: str) -> List[str]:
    return [item.strip() for item in raw_value.split(",") if item.strip()]


def resolve_torch_dtype(dtype_name: str) -> torch.dtype:
    if dtype_name == "float16":
        return torch.float16
    if dtype_name == "bfloat16":
        return torch.bfloat16
    if dtype_name == "float32":
        return torch.float32

    if torch.cuda.is_available():
        if torch.cuda.is_bf16_supported():
            return torch.bfloat16
        return torch.float16

    return torch.float32


def maybe_init_wandb(args: argparse.Namespace) -> None:
    if args.report_to != "wandb":
        return

    if wandb is None:
        raise RuntimeError(
            "wandb is not installed but --report-to wandb was requested."
        )

    # 런 이름을 모델명/도메인 기준으로 잡아 두면 팀원이 대시보드에서 실험을 빠르게 찾기 쉽습니다.
    run_name = args.wandb_run_name or build_default_run_name(args)
    wandb.init(project=args.wandb_project, name=run_name)


def build_default_run_name(args: argparse.Namespace) -> str:
    model_suffix = args.model_id.split("/")[-1]
    dataset_suffix = args.dataset_domain or args.feature_type or "all"
    return f"sft-{model_suffix}-{dataset_suffix}"


def load_training_dataset(args: argparse.Namespace) -> Dataset:
    dataset = load_dataset("json", data_files=args.dataset_path, split="train")

    # 데이터셋을 domain / feature_type / recommendation_type 기준으로 잘라 쓸 수 있게 해 두면
    # 팀원이 "merge만 먼저 smoke test" 같은 짧은 실험을 반복하기 편합니다.
    if args.dataset_domain:
        dataset = dataset.filter(lambda row: row.get("dataset_domain") == args.dataset_domain)

    if args.feature_type:
        dataset = dataset.filter(lambda row: row.get("feature_type") == args.feature_type)

    if args.recommendation_type:
        dataset = dataset.filter(
            lambda row: row.get("recommendation_type") == args.recommendation_type
        )

    if args.max_samples is not None:
        dataset = dataset.select(range(min(args.max_samples, len(dataset))))

    if len(dataset) == 0:
        raise ValueError("Filtered dataset is empty. Relax the dataset filter options.")

    return dataset


def format_instruction(sample: dict) -> str:
    # 현재 GitCat 중간 포맷은 prompt / chosen 한 쌍이므로, 학습 입력도 그 구조를 그대로 드러냅니다.
    # 팀원이 raw JSONL을 열어 봤을 때와 trainer가 읽는 최종 텍스트가 거의 1:1로 대응되도록 유지합니다.
    return (
        f"### Instruction:\n{sample['prompt']}\n\n"
        f"### Response:\n{sample['chosen']}"
    )


def build_tokenizer(model_id: str) -> AutoTokenizer:
    tokenizer = AutoTokenizer.from_pretrained(model_id)

    # causal LM 계열은 pad token이 비어 있는 경우가 잦습니다.
    # eos_token을 pad token으로 재사용해 두면 batch padding 시 바로 학습을 시작할 수 있습니다.
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    tokenizer.padding_side = "right"
    return tokenizer


def build_model(args: argparse.Namespace, torch_dtype: torch.dtype) -> AutoModelForCausalLM:
    model = AutoModelForCausalLM.from_pretrained(
        args.model_id,
        device_map="auto",
        torch_dtype=torch_dtype,
    )

    if args.gradient_checkpointing:
        model.gradient_checkpointing_enable()
        # gradient checkpointing과 cache는 함께 쓰면 경고가 나므로 학습 시점에 꺼 둡니다.
        model.config.use_cache = False

    return model


def build_lora_config(args: argparse.Namespace) -> LoraConfig:
    return LoraConfig(
        r=args.lora_r,
        lora_alpha=args.lora_alpha,
        target_modules=parse_csv_list(args.lora_target_modules),
        lora_dropout=args.lora_dropout,
        bias="none",
        task_type=TaskType.CAUSAL_LM,
    )


def build_training_args(args: argparse.Namespace, torch_dtype: torch.dtype) -> TrainingArguments:
    report_to: List[str] = [] if args.report_to == "none" else [args.report_to]

    return TrainingArguments(
        output_dir=args.output_dir,
        per_device_train_batch_size=args.per_device_train_batch_size,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        learning_rate=args.learning_rate,
        num_train_epochs=args.num_train_epochs,
        max_steps=args.max_steps,
        logging_steps=args.logging_steps,
        save_steps=args.save_steps,
        save_total_limit=args.save_total_limit,
        warmup_ratio=args.warmup_ratio,
        weight_decay=args.weight_decay,
        report_to=report_to,
        bf16=torch.cuda.is_available() and torch_dtype == torch.bfloat16,
        fp16=torch.cuda.is_available() and torch_dtype == torch.float16,
        gradient_checkpointing=args.gradient_checkpointing,
        remove_unused_columns=False,
    )


def print_run_summary(args: argparse.Namespace, dataset: Dataset, torch_dtype: torch.dtype) -> None:
    print("🚀 GitCat SFT-LoRA run configuration")
    print(f" - model_id: {args.model_id}")
    print(f" - dataset_path: {args.dataset_path}")
    print(f" - dataset_size: {len(dataset)}")
    print(f" - dataset_domain: {args.dataset_domain or 'all'}")
    print(f" - feature_type: {args.feature_type or 'all'}")
    print(f" - recommendation_type: {args.recommendation_type or 'all'}")
    print(f" - output_dir: {args.output_dir}")
    print(f" - adapter_output_dir: {args.adapter_output_dir}")
    print(f" - torch_dtype: {torch_dtype}")


def main() -> None:
    args = parse_args()
    os.makedirs(args.output_dir, exist_ok=True)
    os.makedirs(args.adapter_output_dir, exist_ok=True)

    maybe_init_wandb(args)

    dataset = load_training_dataset(args)
    torch_dtype = resolve_torch_dtype(args.torch_dtype)
    print_run_summary(args, dataset, torch_dtype)

    tokenizer = build_tokenizer(args.model_id)
    model = build_model(args, torch_dtype)
    lora_config = build_lora_config(args)
    training_args = build_training_args(args, torch_dtype)

    trainer = SFTTrainer(
        model=model,
        train_dataset=dataset,
        peft_config=lora_config,
        formatting_func=format_instruction,
        max_seq_length=args.max_seq_length,
        tokenizer=tokenizer,
        args=training_args,
    )

    print("🚀 SFT-LoRA 학습을 시작합니다!")
    trainer.train()

    trainer.model.save_pretrained(args.adapter_output_dir)
    tokenizer.save_pretrained(args.adapter_output_dir)
    print(f"✅ 학습 완료 및 LoRA 어댑터 저장 완료: {args.adapter_output_dir}")


if __name__ == "__main__":
    main()
